-- MySQL Script generated by MySQL Workbench
-- Mon Nov  2 17:27:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DispurDB
-- -----------------------------------------------------
-- The database for our Broadband connections, employees, customers and relationships among them

-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `Cust_ID` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Contact_No` VARCHAR(15) NULL,
  `Add` VARCHAR(45) NULL,
  PRIMARY KEY (`Cust_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `Emp_ID` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Designation` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Emp_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Plan` ;

CREATE TABLE IF NOT EXISTS `Plan` (
  `Plan_ID` VARCHAR(15) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Type` INT NOT NULL,
  `Tarrif` INT NOT NULL,
  `Validity` INT NOT NULL,
  `Rental` VARCHAR(45) NULL,
  `Active` BIT(1) NOT NULL,
  PRIMARY KEY (`Plan_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subscription` ;

CREATE TABLE IF NOT EXISTS `Subscription` (
  `Sub_ID` INT NOT NULL,
  `Cust_ID` VARCHAR(15) NOT NULL,
  `Plan_ID` VARCHAR(15) NOT NULL,
  `Sub_date` DATE NOT NULL,
  PRIMARY KEY (`Sub_ID`))
ENGINE = InnoDB;

CREATE INDEX `Cust_ID_idx` ON `Subscription` (`Cust_ID` ASC) VISIBLE;

CREATE INDEX `Plain_ID_idx` ON `Subscription` (`Plan_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Usage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usage` ;

CREATE TABLE IF NOT EXISTS `Usage` (
  `Use_ID` INT NOT NULL,
  `Sub_ID` INT NOT NULL,
  `Duration` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Plan_Type` INT NOT NULL,
  PRIMARY KEY (`Use_ID`))
ENGINE = InnoDB;

CREATE INDEX `Sub_ID_idx` ON `Usage` (`Sub_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `ID` VARCHAR(15) NOT NULL,
  `Active` INT NOT NULL,
  `Staff` INT NOT NULL,
  `email_ID` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
