# Generated by Django 2.2.2 on 2020-11-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Registration_Id',
        ),
    ]
